apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-12T03:51:25Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "109707"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hasher
  uid: fd273cd5-ac5f-11ea-9b88-02425219b745
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: 172.17.0.222:5000/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-12T03:51:44Z"
    lastUpdateTime: "2020-06-12T03:51:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-12T03:51:25Z"
    lastUpdateTime: "2020-06-12T03:51:44Z"
    message: ReplicaSet "hasher-6bd4b98bdb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
